apiVersion: linkerd.io/v1alpha2
kind: ServiceProfile
metadata:
  creationTimestamp: null
  name: signup-service.sweettv.svc.cluster.local
  namespace: sweettv
spec:
  routes:
  - condition:
      method: POST
      pathRegex: /signup_service\.SignupService/SetPhone
    name: /signup_service.SignupService/SetPhone
  - condition:
      method: POST
      pathRegex: /SignupService/SetPhone
    name: /SignupService/SetPhone
  - condition:
      method: POST
      pathRegex: /SignupService/SetPhone\.json
    name: /SignupService/SetPhone.json
  - condition:
      method: POST
      pathRegex: /signup_service\.SignupService/SetCode
    name: /signup_service.SignupService/SetCode
  - condition:
      method: POST
      pathRegex: /SignupService/SetCode
    name: /SignupService/SetCode
  - condition:
      method: POST
      pathRegex: /SignupService/SetCode\.json
    name: /SignupService/SetCode.json
  - condition:
      method: POST
      pathRegex: /signup_service\.SignupService/GetPartnerCode
    name: /signup_service.SignupService/GetPartnerCode
  - condition:
      method: POST
      pathRegex: /SignupService/GetPartnerCode
    name: /SignupService/GetPartnerCode
  - condition:
      method: POST
      pathRegex: /SignupService/GetPartnerCode\.json
    name: /SignupService/GetPartnerCode.json
  - condition:
      method: POST
      pathRegex: /signup_service\.SignupService/Auth
    name: /signup_service.SignupService/Auth
  - condition:
      method: POST
      pathRegex: /SignupService/Auth
    name: /SignupService/Auth
  - condition:
      method: POST
      pathRegex: /SignupService/Auth\.json
    name: /SignupService/Auth.json
  - condition:
      method: POST
      pathRegex: /signup_service\.SignupService/AuthCheck
    name: /signup_service.SignupService/AuthCheck
  - condition:
      method: POST
      pathRegex: /SignupService/AuthCheck
    name: /SignupService/AuthCheck
  - condition:
      method: POST
      pathRegex: /SignupService/AuthCheck\.json
    name: /SignupService/AuthCheck.json
  - condition:
      method: POST
      pathRegex: /signup_service\.SignupService/Logout
    name: /signup_service.SignupService/Logout
  - condition:
      method: POST
      pathRegex: /SignupService/Logout
    name: /SignupService/Logout
  - condition:
      method: POST
      pathRegex: /SignupService/Logout\.json
    name: /SignupService/Logout.json
  - condition:
      method: POST
      pathRegex: /signup_service\.SignupService/CodeAuthTransactionStart
    name: /signup_service.SignupService/CodeAuthTransactionStart
  - condition:
      method: POST
      pathRegex: /SignupService/CodeAuthTransactionStart
    name: /SignupService/CodeAuthTransactionStart
  - condition:
      method: POST
      pathRegex: /SignupService/CodeAuthTransactionStart\.json
    name: /SignupService/CodeAuthTransactionStart.json
  - condition:
      method: POST
      pathRegex: /signup_service\.SignupService/CodeAuthTransactionUpdate
    name: /signup_service.SignupService/CodeAuthTransactionUpdate
  - condition:
      method: POST
      pathRegex: /SignupService/CodeAuthTransactionUpdate
    name: /SignupService/CodeAuthTransactionUpdate
  - condition:
      method: POST
      pathRegex: /SignupService/CodeAuthTransactionUpdate\.json
    name: /SignupService/CodeAuthTransactionUpdate.json
  - condition:
      method: POST
      pathRegex: /signup_service\.SignupService/CodeAuthTransactionSetPhone
    name: /signup_service.SignupService/CodeAuthTransactionSetPhone
  - condition:
      method: POST
      pathRegex: /SignupService/CodeAuthTransactionSetPhone
    name: /SignupService/CodeAuthTransactionSetPhone
  - condition:
      method: POST
      pathRegex: /SignupService/CodeAuthTransactionSetPhone\.json
    name: /SignupService/CodeAuthTransactionSetPhone.json
  - condition:
      method: POST
      pathRegex: /signup_service\.SignupService/CodeAuthTransactionSetCode
    name: /signup_service.SignupService/CodeAuthTransactionSetCode
  - condition:
      method: POST
      pathRegex: /SignupService/CodeAuthTransactionSetCode
    name: /SignupService/CodeAuthTransactionSetCode
  - condition:
      method: POST
      pathRegex: /SignupService/CodeAuthTransactionSetCode\.json
    name: /SignupService/CodeAuthTransactionSetCode.json
