// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: tv_service/stream.proto

package tv_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StreamScheme int32

const (
	StreamScheme_MULTICAST_UDP      StreamScheme = 1
	StreamScheme_MULTICAST_SUDP     StreamScheme = 2
	StreamScheme_UNICAST_UDP        StreamScheme = 3
	StreamScheme_UNICAST_SUDP       StreamScheme = 4
	StreamScheme_HTTP_UDP           StreamScheme = 5
	StreamScheme_HTTP_SUDP          StreamScheme = 6
	StreamScheme_HTTP_HLS           StreamScheme = 7
	StreamScheme_HTTP_HLS_TIMESHIFT StreamScheme = 8
	StreamScheme_HTTPS_HLS_DRM      StreamScheme = 9
	StreamScheme_HTTPS_DASH_DRM     StreamScheme = 10
	StreamScheme_HTTPS_HLS_AES_128  StreamScheme = 11
)

// Enum value maps for StreamScheme.
var (
	StreamScheme_name = map[int32]string{
		1:  "MULTICAST_UDP",
		2:  "MULTICAST_SUDP",
		3:  "UNICAST_UDP",
		4:  "UNICAST_SUDP",
		5:  "HTTP_UDP",
		6:  "HTTP_SUDP",
		7:  "HTTP_HLS",
		8:  "HTTP_HLS_TIMESHIFT",
		9:  "HTTPS_HLS_DRM",
		10: "HTTPS_DASH_DRM",
		11: "HTTPS_HLS_AES_128",
	}
	StreamScheme_value = map[string]int32{
		"MULTICAST_UDP":      1,
		"MULTICAST_SUDP":     2,
		"UNICAST_UDP":        3,
		"UNICAST_SUDP":       4,
		"HTTP_UDP":           5,
		"HTTP_SUDP":          6,
		"HTTP_HLS":           7,
		"HTTP_HLS_TIMESHIFT": 8,
		"HTTPS_HLS_DRM":      9,
		"HTTPS_DASH_DRM":     10,
		"HTTPS_HLS_AES_128":  11,
	}
)

func (x StreamScheme) Enum() *StreamScheme {
	p := new(StreamScheme)
	*p = x
	return p
}

func (x StreamScheme) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StreamScheme) Descriptor() protoreflect.EnumDescriptor {
	return file_tv_service_stream_proto_enumTypes[0].Descriptor()
}

func (StreamScheme) Type() protoreflect.EnumType {
	return &file_tv_service_stream_proto_enumTypes[0]
}

func (x StreamScheme) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *StreamScheme) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = StreamScheme(num)
	return nil
}

// Deprecated: Use StreamScheme.Descriptor instead.
func (StreamScheme) EnumDescriptor() ([]byte, []int) {
	return file_tv_service_stream_proto_rawDescGZIP(), []int{0}
}

var File_tv_service_stream_proto protoreflect.FileDescriptor

var file_tv_service_stream_proto_rawDesc = []byte{
	0x0a, 0x17, 0x74, 0x76, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x73, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x74, 0x76, 0x5f, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2a, 0xd9, 0x01, 0x0a, 0x0c, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x53, 0x63, 0x68, 0x65, 0x6d, 0x65, 0x12, 0x11, 0x0a, 0x0d, 0x4d, 0x55, 0x4c, 0x54, 0x49, 0x43,
	0x41, 0x53, 0x54, 0x5f, 0x55, 0x44, 0x50, 0x10, 0x01, 0x12, 0x12, 0x0a, 0x0e, 0x4d, 0x55, 0x4c,
	0x54, 0x49, 0x43, 0x41, 0x53, 0x54, 0x5f, 0x53, 0x55, 0x44, 0x50, 0x10, 0x02, 0x12, 0x0f, 0x0a,
	0x0b, 0x55, 0x4e, 0x49, 0x43, 0x41, 0x53, 0x54, 0x5f, 0x55, 0x44, 0x50, 0x10, 0x03, 0x12, 0x10,
	0x0a, 0x0c, 0x55, 0x4e, 0x49, 0x43, 0x41, 0x53, 0x54, 0x5f, 0x53, 0x55, 0x44, 0x50, 0x10, 0x04,
	0x12, 0x0c, 0x0a, 0x08, 0x48, 0x54, 0x54, 0x50, 0x5f, 0x55, 0x44, 0x50, 0x10, 0x05, 0x12, 0x0d,
	0x0a, 0x09, 0x48, 0x54, 0x54, 0x50, 0x5f, 0x53, 0x55, 0x44, 0x50, 0x10, 0x06, 0x12, 0x0c, 0x0a,
	0x08, 0x48, 0x54, 0x54, 0x50, 0x5f, 0x48, 0x4c, 0x53, 0x10, 0x07, 0x12, 0x16, 0x0a, 0x12, 0x48,
	0x54, 0x54, 0x50, 0x5f, 0x48, 0x4c, 0x53, 0x5f, 0x54, 0x49, 0x4d, 0x45, 0x53, 0x48, 0x49, 0x46,
	0x54, 0x10, 0x08, 0x12, 0x11, 0x0a, 0x0d, 0x48, 0x54, 0x54, 0x50, 0x53, 0x5f, 0x48, 0x4c, 0x53,
	0x5f, 0x44, 0x52, 0x4d, 0x10, 0x09, 0x12, 0x12, 0x0a, 0x0e, 0x48, 0x54, 0x54, 0x50, 0x53, 0x5f,
	0x44, 0x41, 0x53, 0x48, 0x5f, 0x44, 0x52, 0x4d, 0x10, 0x0a, 0x12, 0x15, 0x0a, 0x11, 0x48, 0x54,
	0x54, 0x50, 0x53, 0x5f, 0x48, 0x4c, 0x53, 0x5f, 0x41, 0x45, 0x53, 0x5f, 0x31, 0x32, 0x38, 0x10,
	0x0b, 0x42, 0x22, 0x5a, 0x20, 0x67, 0x69, 0x74, 0x6c, 0x61, 0x62, 0x2e, 0x73, 0x77, 0x65, 0x65,
	0x74, 0x2e, 0x74, 0x76, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x76, 0x5f, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65,
}

var (
	file_tv_service_stream_proto_rawDescOnce sync.Once
	file_tv_service_stream_proto_rawDescData = file_tv_service_stream_proto_rawDesc
)

func file_tv_service_stream_proto_rawDescGZIP() []byte {
	file_tv_service_stream_proto_rawDescOnce.Do(func() {
		file_tv_service_stream_proto_rawDescData = protoimpl.X.CompressGZIP(file_tv_service_stream_proto_rawDescData)
	})
	return file_tv_service_stream_proto_rawDescData
}

var file_tv_service_stream_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_tv_service_stream_proto_goTypes = []interface{}{
	(StreamScheme)(0), // 0: tv_service.StreamScheme
}
var file_tv_service_stream_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tv_service_stream_proto_init() }
func file_tv_service_stream_proto_init() {
	if File_tv_service_stream_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tv_service_stream_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tv_service_stream_proto_goTypes,
		DependencyIndexes: file_tv_service_stream_proto_depIdxs,
		EnumInfos:         file_tv_service_stream_proto_enumTypes,
	}.Build()
	File_tv_service_stream_proto = out.File
	file_tv_service_stream_proto_rawDesc = nil
	file_tv_service_stream_proto_goTypes = nil
	file_tv_service_stream_proto_depIdxs = nil
}
