// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: tv_service/tv_show.proto

package tv_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Record struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChannelId *int32  `protobuf:"varint,1,req,name=channel_id,json=channelId" json:"channel_id,omitempty"`
	EpgId     *int32  `protobuf:"varint,2,opt,name=epg_id,json=epgId" json:"epg_id,omitempty"`
	Title     *string `protobuf:"bytes,3,opt,name=title" json:"title,omitempty"`
	Available *bool   `protobuf:"varint,4,opt,name=available,def=1" json:"available,omitempty"`
	Tariffs   []int32 `protobuf:"varint,5,rep,name=tariffs" json:"tariffs,omitempty"`
	ImageUrl  *string `protobuf:"bytes,6,opt,name=image_url,json=imageUrl" json:"image_url,omitempty"`
}

// Default values for Record fields.
const (
	Default_Record_Available = bool(true)
)

func (x *Record) Reset() {
	*x = Record{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tv_service_tv_show_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_tv_service_tv_show_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
	return file_tv_service_tv_show_proto_rawDescGZIP(), []int{0}
}

func (x *Record) GetChannelId() int32 {
	if x != nil && x.ChannelId != nil {
		return *x.ChannelId
	}
	return 0
}

func (x *Record) GetEpgId() int32 {
	if x != nil && x.EpgId != nil {
		return *x.EpgId
	}
	return 0
}

func (x *Record) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *Record) GetAvailable() bool {
	if x != nil && x.Available != nil {
		return *x.Available
	}
	return Default_Record_Available
}

func (x *Record) GetTariffs() []int32 {
	if x != nil {
		return x.Tariffs
	}
	return nil
}

func (x *Record) GetImageUrl() string {
	if x != nil && x.ImageUrl != nil {
		return *x.ImageUrl
	}
	return ""
}

type TvShow struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id             *int32    `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Title          *string   `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
	Description    *string   `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
	LastShowDate   *string   `protobuf:"bytes,4,opt,name=last_show_date,json=lastShowDate" json:"last_show_date,omitempty"`
	ProductionYear *int32    `protobuf:"varint,5,opt,name=production_year,json=productionYear" json:"production_year,omitempty"`
	Duration       *int32    `protobuf:"varint,6,opt,name=duration" json:"duration,omitempty"`
	AgeLimit       *int32    `protobuf:"varint,7,opt,name=age_limit,json=ageLimit" json:"age_limit,omitempty"`
	Rating         *float32  `protobuf:"fixed32,8,opt,name=rating" json:"rating,omitempty"`
	PosterUrl      *string   `protobuf:"bytes,9,opt,name=poster_url,json=posterUrl" json:"poster_url,omitempty"`
	BannerUrl      *string   `protobuf:"bytes,10,opt,name=banner_url,json=bannerUrl" json:"banner_url,omitempty"`
	Genres         []int32   `protobuf:"varint,11,rep,name=genres" json:"genres,omitempty"`
	People         []int32   `protobuf:"varint,12,rep,name=people" json:"people,omitempty"`
	Slug           *string   `protobuf:"bytes,13,opt,name=slug" json:"slug,omitempty"`
	TrailerUrl     *string   `protobuf:"bytes,14,opt,name=trailer_url,json=trailerUrl" json:"trailer_url,omitempty"`
	Records        []*Record `protobuf:"bytes,15,rep,name=records" json:"records,omitempty"`
}

func (x *TvShow) Reset() {
	*x = TvShow{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tv_service_tv_show_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TvShow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TvShow) ProtoMessage() {}

func (x *TvShow) ProtoReflect() protoreflect.Message {
	mi := &file_tv_service_tv_show_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TvShow.ProtoReflect.Descriptor instead.
func (*TvShow) Descriptor() ([]byte, []int) {
	return file_tv_service_tv_show_proto_rawDescGZIP(), []int{1}
}

func (x *TvShow) GetId() int32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *TvShow) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *TvShow) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *TvShow) GetLastShowDate() string {
	if x != nil && x.LastShowDate != nil {
		return *x.LastShowDate
	}
	return ""
}

func (x *TvShow) GetProductionYear() int32 {
	if x != nil && x.ProductionYear != nil {
		return *x.ProductionYear
	}
	return 0
}

func (x *TvShow) GetDuration() int32 {
	if x != nil && x.Duration != nil {
		return *x.Duration
	}
	return 0
}

func (x *TvShow) GetAgeLimit() int32 {
	if x != nil && x.AgeLimit != nil {
		return *x.AgeLimit
	}
	return 0
}

func (x *TvShow) GetRating() float32 {
	if x != nil && x.Rating != nil {
		return *x.Rating
	}
	return 0
}

func (x *TvShow) GetPosterUrl() string {
	if x != nil && x.PosterUrl != nil {
		return *x.PosterUrl
	}
	return ""
}

func (x *TvShow) GetBannerUrl() string {
	if x != nil && x.BannerUrl != nil {
		return *x.BannerUrl
	}
	return ""
}

func (x *TvShow) GetGenres() []int32 {
	if x != nil {
		return x.Genres
	}
	return nil
}

func (x *TvShow) GetPeople() []int32 {
	if x != nil {
		return x.People
	}
	return nil
}

func (x *TvShow) GetSlug() string {
	if x != nil && x.Slug != nil {
		return *x.Slug
	}
	return ""
}

func (x *TvShow) GetTrailerUrl() string {
	if x != nil && x.TrailerUrl != nil {
		return *x.TrailerUrl
	}
	return ""
}

func (x *TvShow) GetRecords() []*Record {
	if x != nil {
		return x.Records
	}
	return nil
}

type GetTvShowInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TvShows []int32 `protobuf:"varint,1,rep,name=tv_shows,json=tvShows" json:"tv_shows,omitempty"`
	Offset  *int32  `protobuf:"varint,2,opt,name=offset,def=0" json:"offset,omitempty"`
	Limit   *int32  `protobuf:"varint,3,opt,name=limit,def=0" json:"limit,omitempty"`
}

// Default values for GetTvShowInfoRequest fields.
const (
	Default_GetTvShowInfoRequest_Offset = int32(0)
	Default_GetTvShowInfoRequest_Limit  = int32(0)
)

func (x *GetTvShowInfoRequest) Reset() {
	*x = GetTvShowInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tv_service_tv_show_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTvShowInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTvShowInfoRequest) ProtoMessage() {}

func (x *GetTvShowInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tv_service_tv_show_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTvShowInfoRequest.ProtoReflect.Descriptor instead.
func (*GetTvShowInfoRequest) Descriptor() ([]byte, []int) {
	return file_tv_service_tv_show_proto_rawDescGZIP(), []int{2}
}

func (x *GetTvShowInfoRequest) GetTvShows() []int32 {
	if x != nil {
		return x.TvShows
	}
	return nil
}

func (x *GetTvShowInfoRequest) GetOffset() int32 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return Default_GetTvShowInfoRequest_Offset
}

func (x *GetTvShowInfoRequest) GetLimit() int32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return Default_GetTvShowInfoRequest_Limit
}

type GetTvShowInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TvShows []*TvShow `protobuf:"bytes,2,rep,name=tv_shows,json=tvShows" json:"tv_shows,omitempty"`
}

func (x *GetTvShowInfoResponse) Reset() {
	*x = GetTvShowInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tv_service_tv_show_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTvShowInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTvShowInfoResponse) ProtoMessage() {}

func (x *GetTvShowInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tv_service_tv_show_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTvShowInfoResponse.ProtoReflect.Descriptor instead.
func (*GetTvShowInfoResponse) Descriptor() ([]byte, []int) {
	return file_tv_service_tv_show_proto_rawDescGZIP(), []int{3}
}

func (x *GetTvShowInfoResponse) GetTvShows() []*TvShow {
	if x != nil {
		return x.TvShows
	}
	return nil
}

var File_tv_service_tv_show_proto protoreflect.FileDescriptor

var file_tv_service_tv_show_proto_rawDesc = []byte{
	0x0a, 0x18, 0x74, 0x76, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x74, 0x76, 0x5f,
	0x73, 0x68, 0x6f, 0x77, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x74, 0x76, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x22, 0xaf, 0x01, 0x0a, 0x06, 0x52, 0x65, 0x63, 0x6f, 0x72,
	0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x02, 0x28, 0x05, 0x52, 0x09, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x64,
	0x12, 0x15, 0x0a, 0x06, 0x65, 0x70, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x65, 0x70, 0x67, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x22, 0x0a,
	0x09, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08,
	0x3a, 0x04, 0x74, 0x72, 0x75, 0x65, 0x52, 0x09, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x61, 0x72, 0x69, 0x66, 0x66, 0x73, 0x18, 0x05, 0x20, 0x03,
	0x28, 0x05, 0x52, 0x07, 0x74, 0x61, 0x72, 0x69, 0x66, 0x66, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x69,
	0x6d, 0x61, 0x67, 0x65, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x69, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x72, 0x6c, 0x22, 0xc1, 0x03, 0x0a, 0x06, 0x54, 0x76, 0x53,
	0x68, 0x6f, 0x77, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x02, 0x28, 0x05, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x24, 0x0a, 0x0e, 0x6c,
	0x61, 0x73, 0x74, 0x5f, 0x73, 0x68, 0x6f, 0x77, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0c, 0x6c, 0x61, 0x73, 0x74, 0x53, 0x68, 0x6f, 0x77, 0x44, 0x61, 0x74,
	0x65, 0x12, 0x27, 0x0a, 0x0f, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f,
	0x79, 0x65, 0x61, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x70, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x59, 0x65, 0x61, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x75,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x64, 0x75,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x61, 0x67, 0x65, 0x5f, 0x6c, 0x69,
	0x6d, 0x69, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x61, 0x67, 0x65, 0x4c, 0x69,
	0x6d, 0x69, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x06, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x1d, 0x0a, 0x0a, 0x70,
	0x6f, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x70, 0x6f, 0x73, 0x74, 0x65, 0x72, 0x55, 0x72, 0x6c, 0x12, 0x1d, 0x0a, 0x0a, 0x62, 0x61,
	0x6e, 0x6e, 0x65, 0x72, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x55, 0x72, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x65, 0x6e,
	0x72, 0x65, 0x73, 0x18, 0x0b, 0x20, 0x03, 0x28, 0x05, 0x52, 0x06, 0x67, 0x65, 0x6e, 0x72, 0x65,
	0x73, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x65, 0x6f, 0x70, 0x6c, 0x65, 0x18, 0x0c, 0x20, 0x03, 0x28,
	0x05, 0x52, 0x06, 0x70, 0x65, 0x6f, 0x70, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x6c, 0x75,
	0x67, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x6c, 0x75, 0x67, 0x12, 0x1f, 0x0a,
	0x0b, 0x74, 0x72, 0x61, 0x69, 0x6c, 0x65, 0x72, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x0e, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x74, 0x72, 0x61, 0x69, 0x6c, 0x65, 0x72, 0x55, 0x72, 0x6c, 0x12, 0x2c,
	0x0a, 0x07, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x18, 0x0f, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x12, 0x2e, 0x74, 0x76, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x52, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x52, 0x07, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x22, 0x65, 0x0a, 0x14,
	0x47, 0x65, 0x74, 0x54, 0x76, 0x53, 0x68, 0x6f, 0x77, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x76, 0x5f, 0x73, 0x68, 0x6f, 0x77, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x07, 0x74, 0x76, 0x53, 0x68, 0x6f, 0x77, 0x73, 0x12,
	0x19, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x3a,
	0x01, 0x30, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x17, 0x0a, 0x05, 0x6c, 0x69,
	0x6d, 0x69, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x3a, 0x01, 0x30, 0x52, 0x05, 0x6c, 0x69,
	0x6d, 0x69, 0x74, 0x22, 0x46, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x54, 0x76, 0x53, 0x68, 0x6f, 0x77,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2d, 0x0a, 0x08,
	0x74, 0x76, 0x5f, 0x73, 0x68, 0x6f, 0x77, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12,
	0x2e, 0x74, 0x76, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x54, 0x76, 0x53, 0x68,
	0x6f, 0x77, 0x52, 0x07, 0x74, 0x76, 0x53, 0x68, 0x6f, 0x77, 0x73, 0x42, 0x22, 0x5a, 0x20, 0x67,
	0x69, 0x74, 0x6c, 0x61, 0x62, 0x2e, 0x73, 0x77, 0x65, 0x65, 0x74, 0x2e, 0x74, 0x76, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x76, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
}

var (
	file_tv_service_tv_show_proto_rawDescOnce sync.Once
	file_tv_service_tv_show_proto_rawDescData = file_tv_service_tv_show_proto_rawDesc
)

func file_tv_service_tv_show_proto_rawDescGZIP() []byte {
	file_tv_service_tv_show_proto_rawDescOnce.Do(func() {
		file_tv_service_tv_show_proto_rawDescData = protoimpl.X.CompressGZIP(file_tv_service_tv_show_proto_rawDescData)
	})
	return file_tv_service_tv_show_proto_rawDescData
}

var file_tv_service_tv_show_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_tv_service_tv_show_proto_goTypes = []interface{}{
	(*Record)(nil),                // 0: tv_service.Record
	(*TvShow)(nil),                // 1: tv_service.TvShow
	(*GetTvShowInfoRequest)(nil),  // 2: tv_service.GetTvShowInfoRequest
	(*GetTvShowInfoResponse)(nil), // 3: tv_service.GetTvShowInfoResponse
}
var file_tv_service_tv_show_proto_depIdxs = []int32{
	0, // 0: tv_service.TvShow.records:type_name -> tv_service.Record
	1, // 1: tv_service.GetTvShowInfoResponse.tv_shows:type_name -> tv_service.TvShow
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_tv_service_tv_show_proto_init() }
func file_tv_service_tv_show_proto_init() {
	if File_tv_service_tv_show_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tv_service_tv_show_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Record); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tv_service_tv_show_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TvShow); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tv_service_tv_show_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTvShowInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tv_service_tv_show_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTvShowInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tv_service_tv_show_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tv_service_tv_show_proto_goTypes,
		DependencyIndexes: file_tv_service_tv_show_proto_depIdxs,
		MessageInfos:      file_tv_service_tv_show_proto_msgTypes,
	}.Build()
	File_tv_service_tv_show_proto = out.File
	file_tv_service_tv_show_proto_rawDesc = nil
	file_tv_service_tv_show_proto_goTypes = nil
	file_tv_service_tv_show_proto_depIdxs = nil
}
